"""empty message

Revision ID: 39f7fe2e9cde
Revises: 
Create Date: 2020-05-20 18:43:05.873605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f7fe2e9cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdet',
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('emailid', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('emailid')
    )
    op.drop_table('usercred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercred',
    sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('emailID', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('emailID', name='usercred_pkey')
    )
    op.drop_table('userdet')
    # ### end Alembic commands ###
